// Generated by Selenium IDE
import org.junit.Test;
import org.junit.Before;
import org.junit.After;
import static org.junit.Assert.*;
import static org.hamcrest.CoreMatchers.is;
import static org.hamcrest.core.IsNot.not;
import org.openqa.selenium.By;
import org.openqa.selenium.WebDriver;
import org.openqa.selenium.firefox.FirefoxDriver;
import org.openqa.selenium.chrome.ChromeDriver;
import org.openqa.selenium.remote.RemoteWebDriver;
import org.openqa.selenium.remote.DesiredCapabilities;
import org.openqa.selenium.Dimension;
import org.openqa.selenium.WebElement;
import org.openqa.selenium.interactions.Actions;
import org.openqa.selenium.support.ui.ExpectedConditions;
import org.openqa.selenium.support.ui.WebDriverWait;
import org.openqa.selenium.JavascriptExecutor;
import org.openqa.selenium.Alert;
import org.openqa.selenium.Keys;
import java.util.*;
import java.net.MalformedURLException;
import java.net.URL;
public class ListarVeterinarioTest {
  private WebDriver driver;
  private Map<String, Object> vars;
  JavascriptExecutor js;
  @Before
  public void setUp() {
    driver = new ChromeDriver();
    js = (JavascriptExecutor) driver;
    vars = new HashMap<String, Object>();
  }
  @After
  public void tearDown() {
    driver.quit();
  }
  @Test
  public void listarVeterinario() {
    driver.get("http://localhost:8080/home");
    driver.manage().window().setSize(new Dimension(894, 816));
    driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2) > span")).click();
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(2) > span")).getText(), is("Conceicao Evaristo"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(3) > span")).getText(), is("pequenos"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(4) > span")).getText(), is("conceicao@gmail.com"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(2) > td:nth-child(5) > span")).getText(), is("3500.00"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(2) > span")).getText(), is("Erica Queiroz Pinto"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(3) > span")).getText(), is("grandes"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(4) > span")).getText(), is("erica@gmail.com"));
    assertThat(driver.findElement(By.cssSelector("tr:nth-child(3) > td:nth-child(5) > span")).getText(), is("4500.00"));
  }
}
